/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as InfiniteScrollRouteImport } from './routes/infinite-scroll'
import { Route as FormBuilderRouteImport } from './routes/form-builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataTableIndexRouteImport } from './routes/data-table.index'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const InfiniteScrollRoute = InfiniteScrollRouteImport.update({
  id: '/infinite-scroll',
  path: '/infinite-scroll',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderRoute = FormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTableIndexRoute = DataTableIndexRouteImport.update({
  id: '/data-table/',
  path: '/data-table/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRoute
  '/infinite-scroll': typeof InfiniteScrollRoute
  '/wizard': typeof WizardRoute
  '/data-table': typeof DataTableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRoute
  '/infinite-scroll': typeof InfiniteScrollRoute
  '/wizard': typeof WizardRoute
  '/data-table': typeof DataTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form-builder': typeof FormBuilderRoute
  '/infinite-scroll': typeof InfiniteScrollRoute
  '/wizard': typeof WizardRoute
  '/data-table/': typeof DataTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/form-builder'
    | '/infinite-scroll'
    | '/wizard'
    | '/data-table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form-builder' | '/infinite-scroll' | '/wizard' | '/data-table'
  id:
    | '__root__'
    | '/'
    | '/form-builder'
    | '/infinite-scroll'
    | '/wizard'
    | '/data-table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormBuilderRoute: typeof FormBuilderRoute
  InfiniteScrollRoute: typeof InfiniteScrollRoute
  WizardRoute: typeof WizardRoute
  DataTableIndexRoute: typeof DataTableIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infinite-scroll': {
      id: '/infinite-scroll'
      path: '/infinite-scroll'
      fullPath: '/infinite-scroll'
      preLoaderRoute: typeof InfiniteScrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder': {
      id: '/form-builder'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-table/': {
      id: '/data-table/'
      path: '/data-table'
      fullPath: '/data-table'
      preLoaderRoute: typeof DataTableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormBuilderRoute: FormBuilderRoute,
  InfiniteScrollRoute: InfiniteScrollRoute,
  WizardRoute: WizardRoute,
  DataTableIndexRoute: DataTableIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
